on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: HTML to PDF (chrome)
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: index.html
          outputFile: resume.pdf
          pdfOptions: '{"format": "A4", "pageRanges": "1"}'

